# Generated by Django 2.0.3 on 2019-12-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191204_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.School'),
        ),
    ]
