# Generated by Django 2.1.5 on 2019-12-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191204_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_school', to='projects.School'),
        ),
    ]
