# Generated by Django 2.1.5 on 2019-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img',
            field=models.CharField(default='', max_length=40),
        ),
    ]
